name: CI

on:
  push:
    branches:
      - master

env:
  PORT: "3001"

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Super-Linter
        uses: github/super-linter@v5
        with:
          validate_all_codebase: false
          default_branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies (Frontend)
        run: npm install
        working-directory: packages/react-frontend

      - name: Install Dependencies (Backend)
        run: npm install
        working-directory: packages/express-backend

      - name: Build (Frontend)
        run: npm run build
        working-directory: packages/react-frontend

      - name: Build (Backend)
        run: npm run build
        working-directory: packages/express-backend

      # - name: Build
      #   run: npm run build

      - name: Run Tests (Frontend)
        run: npm test
        working-directory: packages/react-frontend

      # - name: Run Tests (Backend)
      #   run: npm test
      #   working-directory: packages/express-backend

      - name: Job complete
        run: echo "Job complete"
